//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DifferenzXamarinDemo.LanguageResources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DifferenzXamarinDemo.LanguageResources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TITLE_ALERT {
            get {
                return ResourceManager.GetString("TITLE_ALERT", resourceCulture);
            }
        }
        
        internal static string TITLE_ERROR {
            get {
                return ResourceManager.GetString("TITLE_ERROR", resourceCulture);
            }
        }
        
        internal static string TITLE_SUCCESS {
            get {
                return ResourceManager.GetString("TITLE_SUCCESS", resourceCulture);
            }
        }
        
        internal static string TITLE_VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("TITLE_VALIDATION_ERROR", resourceCulture);
            }
        }
        
        internal static string MESSAGE_SUCCESS_DATA_SAVE {
            get {
                return ResourceManager.GetString("MESSAGE_SUCCESS_DATA_SAVE", resourceCulture);
            }
        }
        
        internal static string MESSAGE_SUCCESS_DATA_UPDATED {
            get {
                return ResourceManager.GetString("MESSAGE_SUCCESS_DATA_UPDATED", resourceCulture);
            }
        }
        
        internal static string MESSAGE_ERROR_INSERT_ALL_DATA {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_INSERT_ALL_DATA", resourceCulture);
            }
        }
        
        internal static string MESSAGE_ERROR_EMAIL_PASSWORD_ERROR {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_EMAIL_PASSWORD_ERROR", resourceCulture);
            }
        }
        
        internal static string MESSAGE_ERROR_SOMETHING_WENT_WRONG_WITH_USER_LOGIN {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_SOMETHING_WENT_WRONG_WITH_USER_LOGIN", resourceCulture);
            }
        }
        
        internal static string MESSAGE_ERROR_SESSION_EXPIRED {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_SESSION_EXPIRED", resourceCulture);
            }
        }
        
        internal static string MESSAGE_ERROR_SOMETHING_WENT_WRONG {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_SOMETHING_WENT_WRONG", resourceCulture);
            }
        }
        
        internal static string MESSAGE_ERROR_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_INVALID_EMAIL", resourceCulture);
            }
        }
        
        internal static string MESSAGE_ERROR_INVALID_CONTACT_NO {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_INVALID_CONTACT_NO", resourceCulture);
            }
        }
        
        internal static string MESSAGE_ERROR_NO_INTERNET {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_NO_INTERNET", resourceCulture);
            }
        }
        
        internal static string TEXT_OK {
            get {
                return ResourceManager.GetString("TEXT_OK", resourceCulture);
            }
        }
        
        internal static string TEXT_LOGOUT {
            get {
                return ResourceManager.GetString("TEXT_LOGOUT", resourceCulture);
            }
        }
        
        internal static string TEXT_CANCEL {
            get {
                return ResourceManager.GetString("TEXT_CANCEL", resourceCulture);
            }
        }
        
        internal static string TEXT_UPDATE {
            get {
                return ResourceManager.GetString("TEXT_UPDATE", resourceCulture);
            }
        }
        
        internal static string TEXT_DELETE {
            get {
                return ResourceManager.GetString("TEXT_DELETE", resourceCulture);
            }
        }
        
        internal static string TEXT_SAVE {
            get {
                return ResourceManager.GetString("TEXT_SAVE", resourceCulture);
            }
        }
        
        internal static string TEXT_ADD {
            get {
                return ResourceManager.GetString("TEXT_ADD", resourceCulture);
            }
        }
        
        internal static string TEXT_LOGIN {
            get {
                return ResourceManager.GetString("TEXT_LOGIN", resourceCulture);
            }
        }
        
        internal static string TEXT_DETAIL {
            get {
                return ResourceManager.GetString("TEXT_DETAIL", resourceCulture);
            }
        }
        
        internal static string Text_ADDRESS_BOOK {
            get {
                return ResourceManager.GetString("Text_ADDRESS_BOOK", resourceCulture);
            }
        }
        
        internal static string TEXT_EMAIL {
            get {
                return ResourceManager.GetString("TEXT_EMAIL", resourceCulture);
            }
        }
        
        internal static string TEXT_PASSWORD {
            get {
                return ResourceManager.GetString("TEXT_PASSWORD", resourceCulture);
            }
        }
        
        internal static string TEXT_LOG_IN {
            get {
                return ResourceManager.GetString("TEXT_LOG_IN", resourceCulture);
            }
        }
        
        internal static string TEXT_OR {
            get {
                return ResourceManager.GetString("TEXT_OR", resourceCulture);
            }
        }
        
        internal static string TEXT_LOGIN_WITH_FACEBOOK {
            get {
                return ResourceManager.GetString("TEXT_LOGIN_WITH_FACEBOOK", resourceCulture);
            }
        }
        
        internal static string TEXT_NAME {
            get {
                return ResourceManager.GetString("TEXT_NAME", resourceCulture);
            }
        }
        
        internal static string TEXT_CONTACT_NUMBER {
            get {
                return ResourceManager.GetString("TEXT_CONTACT_NUMBER", resourceCulture);
            }
        }
        
        internal static string TEXT_ACTIVE {
            get {
                return ResourceManager.GetString("TEXT_ACTIVE", resourceCulture);
            }
        }
        
        internal static string TEXT_NO_DATA {
            get {
                return ResourceManager.GetString("TEXT_NO_DATA", resourceCulture);
            }
        }
        
        internal static string PLACEHOLDER_PASSWORD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PASSWORD", resourceCulture);
            }
        }
        
        internal static string PLACEHOLDER_EMAIL {
            get {
                return ResourceManager.GetString("PLACEHOLDER_EMAIL", resourceCulture);
            }
        }
        
        internal static string PLACEHOLDER_CONTACT_NO {
            get {
                return ResourceManager.GetString("PLACEHOLDER_CONTACT_NO", resourceCulture);
            }
        }
        
        internal static string PLACEHOLDER_USERNAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_USERNAME", resourceCulture);
            }
        }
        
        internal static string PLACEHOLDER_SEARCH_CONTACT {
            get {
                return ResourceManager.GetString("PLACEHOLDER_SEARCH_CONTACT", resourceCulture);
            }
        }
    }
}
